### ISSUE TITLE
運用について

### ISSUE THREAD

**Issue by yudai-ez** [ichiyanagi-mono/mongo_env#1]
自分のMongoの知識がのベースが古くて恐縮なんですが、MongoDBは運用が大変というイメージがあります。

よく聞く話ではディスクを食いやすく、ディスクの容量を空けるためにrepairDatabaseしようとしても今使用しているディスクの倍のサイズのディスク容量が必要になるため、すでにディスクを半分使用していると詰む、といったものです。

最近はそういうものは解消されてたりするのでしょうか？
または、MongoLabを活用されてたり、そもそも巨大なデータセットを扱わなかったりしてたりするのでしょうか？

**Comment by ichiyanagi-mono** [comment]
ご質問ありがとうございます！

せっかく深いツッコミ頂いたのに申し訳なのですが、弊社でもまだMongoDBは導入検討段階で運用面の知識がありません…。
なのでご質問の内容には答えられないのですが、以下にMongoDBに対しての雑感を書かせてもらいます。

コメントで頂いている通りMongoDBの運用には独特なノウハウが必要であろうという辺りは僕も同意見です。なのでインフラ側から見ると本番導入には勇気のいる選択かなと考えています。
ただ一方でアプリ側から見た際にMongoDBは魅力的な選択肢ではないかとも考えており、今回アプリエンジニア向けに簡単にMongoDBに触る機会を作ろうというのが勉強会の主旨になります。

余談ですが、実際に本番導入する際にはMongoLabのようなホスティングサービスを使うのが正解な気がしつつも、小規模なシステムで導入してノウハウを溜めてみたいなぁというような事を考えています。

**Comment by yudai-ez** [comment]
ご回答ありがとうございます！
なるほど、今は検討段階なんですね。

僕もちょっと触ったことがある程度で具体的な運用ノウハウは無いので恐縮なんですが、自分が使うのであれば

- モックアプリケーションのバックエンド
- 集計で使うスポットのデータストア

など、 **永続化しないデータ** を扱う際に使用すると思います。
アメーバピグやTokyoOtakuModeみたいな使い方する勇気は出ないですね...

